#!/bin/bash
# Copyright 2016 Canonical Ltd.
# Copyright 2017 Link Motion Oy.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation; version 2.1.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Author: Benjamin Zeller <benjamin.zeller@link-motion.com>

pacmd list-modules | grep protocol-tcp &> /dev/null
if [ $? -ne 0 ]; then
        NET_ADDR=$(grep "LXC_ADDR=" "/etc/default/lxc-net" | cut -d'=' -f 2)
        NET_ADDR=${NET_ADDR//\"/}
        if [ ! -z "${NET_ADDR}" ]; then
            echo "Loading with net addr: ${NET_ADDR}"
            pacmd load-module module-native-protocol-tcp auth-ip-acl="127.0.0.1;${NET_ADDR}"
        else
            echo "Loading without net addr"
            pacmd load-module module-native-protocol-tcp
        fi
fi
