#!/bin/bash
set -e

export PATH=/opt/linkmotion/qt/5.8.0/bin:$PATH

QTC_SRC=$1

if [[ -z ${QTC_SRC} ]]; then
  echo "USAGE: ./build [qtc_src]"
  exit 1
fi
QTC_INSTALL="/opt/linkmotion/qtcreator"

QTC_SOURCE=${QTC_SRC} QTC_BUILD=${QTC_SRC} QTC_INSTALL=${QTC_INSTALL} qmake -r
make
sudo make install
set +e
sudo rm -r ${QTC_INSTALL}/share/qtcreator/templates/wizards/linkmotion
set -e
sudo cp -r share/* ${QTC_INSTALL}/share
gdb ${QTC_INSTALL}/bin/qtcreator
